### PR TITLE
TEL-5655: Fix SegFault crash on mod_unimrcp

### PR DESCRIPTION
**Pull request by baloeng**

### CODE REVIEW

**Review by dev-ryanc — CHANGES_REQUESTED** [review]
According to the crash, it happened on line 3767 where it try to execute mpf_dtmf_generator_put_frame. I don't think validating schannel or the mutex may fix the issue. The issue might be the recognizer_data_t* r is null or corrupted

**Comment by baloeng** [comment]
I already checked for recognizer_data_t* r in line 3768. I validated mutex and schannel because we had a similar crash on mutex prior to this crash. [Sample](https://telnyx.slack.com/archives/CK9HD9GNQ/p1682569026903609)

**Comment by dev-ryanc** [comment]
> I already checked for recognizer_data_t* r in line 3768. I validated mutex and schannel because we had a similar crash on mutex prior to this crash. [Sample](https://telnyx.slack.com/archives/CK9HD9GNQ/p1682569026903609)

schannel and mutex is allocated by a memory pool in speech_channel_create. Meaning when the memory pool is deleted after the speech_channel_destroy, schannel and mutex will be deleted at the same time. The problem is that this recog_stream_read might be running in a different thread and probably the issue is a a race condition where it is executed after the speech_channel_destroy and schannel or mutex might be a garbage pointer.

**Comment by mishehu** [comment]
If this is the case that schannel and the mutex may be torn down at the point this PR is to be executed,  when they do get torn down, make sure to set their values back to 0, so that these code changes that Emmanuel is proposing would be reliable, no?

**Comment by baloeng** [comment]
Just checked the crash with the mutex trace again, this seems to be a consequence rather than the cause. Line [3766](https://telnyx.slack.com/archives/CK9HD9GNQ/p1682569026903609) in `recog_stream_read` in the trace tried checking for `r->dtmf_generator_active` (which `r` could now be a null object), this was then followed by switch_mutex_lock() call in switch_apr.c then the seg fault

I've amended the code to only check for` r`

**Review by dev-ryanc — CHANGES_REQUESTED** [review]
- Check recog_asr_close and make sure to set a NULL value for schannel->data;
- In recog_stream_read before it process anything, return immediately if r is NULL

**Pull request closed without merging**
