### PR TITLE
TEL-6126 Comment out RTCP XR handling.

### PR DESCRIPTION
**Pull request by damirn**

### CODE REVIEW

**Review by tajamulTelnyx — APPROVED** [review]
LGTM

**Review by dev-ryanc — CHANGES_REQUESTED** [review]
Can't we just use `offer_rtcp_xr` variable to disable but offer and processing rtcp-xr so no need to comment it out?

**Comment by damirn** [comment]
that would be tricky to get in `static switch_status_t process_rtcp_report(switch_rtp_t *rtp_session, rtcp_msg_t *msg, switch_size_t bytes)`

**Comment by dev-ryanc** [comment]
> that would be tricky to get in `static switch_status_t process_rtcp_report(switch_rtp_t *rtp_session, rtcp_msg_t *msg, switch_size_t bytes)`

It would require passing from sofia -> switch_core_media -> switch_rtp.

Otherwise I would opt to just using macro for now and its default to disable.

**Comment by damirn** [comment]
@dev-ryanc how about this?

**Review by dev-ryanc — APPROVED** [review]
LGTM but do perform another test just to be sure

**Comment by damirn** [comment]
I have retested it again; looks OK (don't want to jinx it though)

**Review by dev-ryanc — APPROVED** [review]

**Pull request merged**
